swagger: '2.0'
info:
  version: 1.0.0

  title: CONGRATULATIONS!!
  description: '<html>
<body>
<br>
  <center><h1>
    YOU WIN A PRIZE <br> FROM <br>JOHN DEERE US
  </h1>
  <h3>ONE CLICK AWAY TO CLAIM IT!</h3>
  <img src="https://www.deere.com/assets/images/region-4/finance/campaigns/black-friday-offers/hero-english/homepage-hero/homepage-hero-bftg-r4k001809-rrd-1366x347.jpg" width="500" height="200">
  
  <br>
<a href="https://example.com"><h1>PLEASE CLICK HERE TO CLAIM YOUR PRIZE!</h1></a>
    </center>
   
   
   <br>
   <br>
   <br>
   <br>
</body>
</html>'

paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
