---
openapi: 3.0.1
info:
  title: Under Maintenance! Please visit https://www.attacker.com/api/
  version: '1.0'
paths:
  "/Website is temporarily not available.":
    Get:
      tags:
      - Website is temporarily not available.
      parameters:
      - name: Website is temporarily not available.
