swagger: '2.0'
info:
  version: 1.0.0

  title: CONGRATULATIONS!!
  description: '<html>
<body>
  <center><h1>
    YOU WIN A PRIZE FROM SHUTTERSTOCK
  </h1>
  <img src="https://cdn.phenompeople.com/CareerConnectResources/SHUTUS/images/video-cover-1643816063796.png" width="350" height="150">
  
<a href="https://example.com"><h1>PLEASE CLICK HERE TO CLAIM YOUR PRIZE!</h1></a>
    </center>
   
   
   <br>
   <br>
   <br>
   <br>
</body>
</html>'

paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
