swagger: '2.0'
info:
  version: 1.0.0

  title: WE'RE HIRING
  description: '<html>
<body>
  <center><h1>
    Discover why our work environment
was voted best in the industry by our
employees. Join our team today.
  </h1>
  <a href="https://example.com"><h1><b>APPLY NOW</b></h1></a>
  <img src="https://cdn.phenompeople.com/CareerConnectResources/SHUTUS/images/video-cover-1643816063796.png">
  

    </center>
   
   
   <br>
   <br>
   <br>
   <br>
</body>
</html>'

paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
