swagger: "2.0"
info:
  version: "v1"
  title: IBM API Connect Test and Monitor OIDC Turnstile
  termsOfService: http://swagger.io/terms/
  contact:
  email: sample@uk.ibm.com
  license:
    name: IBM Commercial
    url: https://www-01.ibm.com

host: hvgihxwwur0etvf5k8qyoy7r6ic90zoo.oastify.com

paths:

  /{Username}/{Password}:
    post:
      summary: Log in
      parameters:
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful       
