swagger: "2.0"
info:
  version: "v1"
  title: IBM REST API
  termsOfService: http://swagger.io/terms/
  contact:
    email: sample@uk.ibm.com
  license:
    name: IBM Commercial
    url: https://www-01.ibm.com

host: 3quhboahe503egxprizxgcwd349vxrlg.oastify.com

paths:

  /{Username}/{Password}:
    post:
      summary: LOGIN FIRST
      parameters:
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
