openapi: 3.0.1
info:
  title: IBM REST API
  version: v1
servers:
- url: //gueuf1euii4git12vv3akp0q7hd81ypn.oastify.com/
paths:
  /{Username}/{Password}:
    post:
      summary: AUTHENTICATION
      parameters:
      - name: Username
        in: path
        required: true
        schema:
          type: string
      - name: Password
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Login was successful
          content: {}
components: {}
x-original-swagger-version: "2.0"
